In [52]:
import numpy as np
import pandas as pd
import os

In [53]:
try:
    import kagglehub
except ModuleNotFoundError:
    !pip install kagglehub --upgrade
    import kagglehub

dataset_slug = "themrityunjaypathak/pandas-practice-dataset"

try:
    print(f"Downloading dataset: {dataset_slug}")
    path = kagglehub.dataset_download(dataset_slug)
    print("Extraction successful!")
    print(f"Path to dataset files: {path}")
except Exception as e:
    print("Error while downloading dataset:")
    print(e)

Downloading dataset: themrityunjaypathak/pandas-practice-dataset
Extraction successful!
Path to dataset files: C:\Users\athar\.cache\kagglehub\datasets\themrityunjaypathak\pandas-practice-dataset\versions\1

In [54]:
dataset_path = r"C:\Users\athar\.cache\kagglehub\datasets\themrityunjaypathak\pandas-practice-dataset\versions\1"
print(os.listdir(dataset_path)

['data.csv']

In [56]:
df = pd.read_csv(os.path.join(dataset_path, "data.csv"))
df.head(5)

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [57]:
df.tail(10)

    Duration          Date  Pulse  Maxpulse  Calories
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [58]:
df.shape

(32, 5)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [60]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [61]:
df["Calories"]

0     409.1
1     479.0
2     340.0
3     282.4
4     406.0
5     300.0
6     374.0
7     253.3
8     195.1
9     269.0
10    329.3
11    250.7
12    250.7
13    345.3
14    379.3
15    275.0
16    215.2
17    300.0
18      NaN
19    323.0
20    243.0
21    364.2
22    282.0
23    300.0
24    246.0
25    334.5
26    250.0
27    241.0
28      NaN
29    280.0
30    380.3
31    243.0
Name: Calories, dtype: float64

In [62]:
df["Calories"].head(5)

0    409.1
1    479.0
2    340.0
3    282.4
4    406.0
Name: Calories, dtype: float64

In [63]:
df["Calories"].tail(5)

27    241.0
28      NaN
29    280.0
30    380.3
31    243.0
Name: Calories, dtype: float64

In [64]:
df["Calories"].shape

(32,)

In [66]:
df[["Date","Calories"]]

            Date  Calories
0   '2020/12/01'     409.1
1   '2020/12/02'     479.0
2   '2020/12/03'     340.0
3   '2020/12/04'     282.4
4   '2020/12/05'     406.0
5   '2020/12/06'     300.0
6   '2020/12/07'     374.0
7   '2020/12/08'     253.3
8   '2020/12/09'     195.1
9   '2020/12/10'     269.0
10  '2020/12/11'     329.3
11  '2020/12/12'     250.7
12  '2020/12/12'     250.7
13  '2020/12/13'     345.3
14  '2020/12/14'     379.3
15  '2020/12/15'     275.0
16  '2020/12/16'     215.2
17  '2020/12/17'     300.0
18  '2020/12/18'       NaN
19  '2020/12/19'     323.0
20  '2020/12/20'     243.0
21  '2020/12/21'     364.2
22           NaN     282.0
23  '2020/12/23'     300.0
24  '2020/12/24'     246.0
25  '2020/12/25'     334.5
26      20201226     250.0
27  '2020/12/27'     241.0
28  '2020/12/28'       NaN
29  '2020/12/29'     280.0
30  '2020/12/30'     380.3
31  '2020/12/31'     243.0

In [67]:
df[["Date","Calories"]].head(2)

           Date  Calories
0  '2020/12/01'     409.1
1  '2020/12/02'     479.0

In [68]:
df.iloc[0]

Duration              60
Date        '2020/12/01'
Pulse                110
Maxpulse             130
Calories           409.1
Name: 0, dtype: object

In [70]:
df.loc[1 , "Calories"]

np.float64(479.0)

In [71]:
df.iloc[0:5, 0:2]

   Duration          Date
0        60  '2020/12/01'
1        60  '2020/12/02'
2        60  '2020/12/03'
3        45  '2020/12/04'
4        45  '2020/12/05'

In [84]:
df["Duration"] > 50

0      True
1      True
2      True
3     False
4     False
5      True
6      True
7      True
8     False
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18    False
19     True
20    False
21     True
22    False
23     True
24    False
25     True
26     True
27     True
28     True
29     True
30     True
31     True
Name: Duration, dtype: bool

In [85]:
if (df.loc[2,'Duration'] > 50):
    print("Excellent")
else:
    print("Not good enough")

Excellent

In [88]:
newdf = df[df['Duration'] > 45]
newdf.head(5)

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
5        60  '2020/12/06'    102       127     300.0
6        60  '2020/12/07'    110       136     374.0

In [92]:
filteredf = df.query("Duration > 45 and Pulse < 100")
filteredf

    Duration          Date  Pulse  Maxpulse  Calories
9         60  '2020/12/10'     98       124     269.0
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
27        60  '2020/12/27'     92       118     241.0
31        60  '2020/12/31'     92       115     243.0

In [93]:
df.isnull().count()

Duration    32
Date        32
Pulse       32
Maxpulse    32
Calories    32
dtype: int64

In [96]:
df.fillna(0)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       0.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45             0    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       0.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [100]:
df = df.dropna()
df.head(10)

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0
5        60  '2020/12/06'    102       127     300.0
6        60  '2020/12/07'    110       136     374.0
7       450  '2020/12/08'    104       134     253.3
8        30  '2020/12/09'    109       133     195.1
9        60  '2020/12/10'     98       124     269.0

In [101]:
df["Calories Burnt / min"] = df['Calories'] / df['Duration']
df.head(10)

   Duration          Date  Pulse  Maxpulse  Calories  Calories Burnt / min
0        60  '2020/12/01'    110       130     409.1              6.818333
1        60  '2020/12/02'    117       145     479.0              7.983333
2        60  '2020/12/03'    103       135     340.0              5.666667
3        45  '2020/12/04'    109       175     282.4              6.275556
4        45  '2020/12/05'    117       148     406.0              9.022222
5        60  '2020/12/06'    102       127     300.0              5.000000
6        60  '2020/12/07'    110       136     374.0              6.233333
7       450  '2020/12/08'    104       134     253.3              0.562889
8        30  '2020/12/09'    109       133     195.1              6.503333
9        60  '2020/12/10'     98       124     269.0              4.483333

In [102]:
df.rename(columns={'Calories Burnt / min':'Calories Burnt / Min'}, inplace=True)
df.head(10)

   Duration          Date  Pulse  Maxpulse  Calories  Calories Burnt / Min
0        60  '2020/12/01'    110       130     409.1              6.818333
1        60  '2020/12/02'    117       145     479.0              7.983333
2        60  '2020/12/03'    103       135     340.0              5.666667
3        45  '2020/12/04'    109       175     282.4              6.275556
4        45  '2020/12/05'    117       148     406.0              9.022222
5        60  '2020/12/06'    102       127     300.0              5.000000
6        60  '2020/12/07'    110       136     374.0              6.233333
7       450  '2020/12/08'    104       134     253.3              0.562889
8        30  '2020/12/09'    109       133     195.1              6.503333
9        60  '2020/12/10'     98       124     269.0              4.483333

In [104]:
output_path = os.path.join(os.getcwd(), "output.csv")
df.to_csv(output_path, index=False)
print(f"File saved at: {output_path}")

File saved at: C:\Users\athar\output.csv